### ISSUE TITLE
"content" handler cannot be channel scoped

### ISSUE THREAD

**Issue by glenjamin** [bakkerthehacker/bramqp#35]
I'm unsure whether this is a problem in practice as the content always follows delivery, which is scoped. Is this guaranteed on the socket?

It does lead to a slightly inconsistent API, where I can subscribe to `"1:basic.deliver"`, but then have to follow it up with a plain `"content"` handler.

**Comment by bakkerthehacker** [comment]
You are right, the channel scoping should have been added to the content in addition to the content.

**Comment by bakkerthehacker** [comment]
Fixed in 92ba4cf and published in 0.3.1
