### ISSUE TITLE
Adding headers to message

### ISSUE THREAD

**Issue by Edgesystems** [bakkerthehacker/bramqp#38]
The message is not published when I add headers. Callback is triggered (which prints "Published message") but the message is not routed to the queue. Am I doing something wrong?

```javascript
var message = [
    'UserUpdate',
    {
        'id': pbx_user_id,
        'pbx_profile_id': new_pbx_schedule_id,
        'pbx_profile_type': 'schedule'
    }
];

msg = JSON.stringify( message );

var table = {
    'headers': {
        'company': {
            type: 'Unsigned 64-bit',
            data: 4
        }
    }
};

app.amqpHandle.content( 1, 'basic', table, msg, function() {
        console.log( 'Published message' );
} );
```

**Comment by Edgesystems** [comment]
If i change to "Signed 32-bit" it works but what about large numbers? Unsigned 32-bit doesnt work either

**Comment by bakkerthehacker** [comment]
bramqp was designed to support both signed and unsigned integers.  however, rabbitmq only uses the signed integers and so, only signed integers appear in the valueTypes.js file.  

For larger numbers there is still a signed 64 bit integer.
