### ISSUE TITLE
removeListener

### ISSUE THREAD

**Issue by giorni** [bakkerthehacker/bramqp#39]
Considering that the 'handle' is an instance of Socket, which is a instance of events.EventEmitter, shouldn't the removeListener work within the library?

I am trying to remove some listeners after a time (handle.on(event)). Is it possible to do in any other way?

**Comment by bakkerthehacker** [comment]
The `handle` is not a socket.  `handle.socket` is the socket passed in.  The `handle` directly sudclasses `EventEmitter`.  

Any method provided by node.js in the [events module](https://nodejs.org/api/events.html#events_event_removelistener) should work.

**Comment by giorni** [comment]
Sorry for that mistake. Thanks for the response.

So, what I am doing here is creating an listener with `handle.on('event')` and after a while trying to remove with `handle.removeListerner('event')`. The removeListener callback is never called and I can see the that there is still a listener for my event using `handle.listeners('event')`. Do you have any idea what can be done different here?

**Comment by bakkerthehacker** [comment]
That sounds correct.  However, without looking at the code, there is not much i can say

**Comment by giorni** [comment]
Here it is.

```javascript
var handle

  function openConnection() {
    bramqp.selectSpecification('rabbitmq/full/amqp0-9-1.stripped.extended', function(err) {
      if (err) logger.error('Starting specification', { source: 'rabbitmq', err: err })

      var socket = net.connect(config.connection, function() {
        bramqp.initializeSocket(socket, function(error, _handle) {
          handle = _handle

          async.series([function(seriesCallback) {
            handle.openAMQPCommunication(config.creds.user, config.creds.pass, true, config.vhost, seriesCallback);
          }, function(seriesCallback) {
            handle.queue.declare(1, config.queue.plans, false, true, false, false, false, {})
            handle.queue.declare(1, config.queue.notify, false, true, false, false, false, {})

            handle.on('queue.declare-ok', function(channel, method, data) {
              logger.info('Queue declared', { queue: data.queue, source: 'rabbitmq' })
            });

            handle.socket.removeListener('queue.declare-ok', function (stream) {
              console.log( 'removed' )
            })
          }])
        })
      })
    })
  }
```

I know it may be not the right and best place to have it, since I would be deleting it anyway, but I just wanted to see it working, and the listener removed.

**Comment by bakkerthehacker** [comment]
My first issue with this is that it is using bramqp 0.1.x initialization.  bramqp 0.1.18 was the latest of these and is almost a year old at this point.  

Secondly, the [removeListener](https://nodejs.org/api/events.html#events_emitter_removelistener_event_listener) function does not take a callback as its second argument.  The second argument must be the function that was used to listen to the event.  

```javascript
listener = function(channel, method, data) {
  logger.info('Queue declared', { queue: data.queue, source: 'rabbitmq' })
}
handle.on('queue.declare-ok', listener)
handle.removeListener('queue.declare-ok', listener)
```

**Comment by giorni** [comment]
Thanks a lot @bakkerthehacker.

Just looked the documentation again. I got confused with the method name being `callback`.
