### ISSUE TITLE
I have a problem of connection TLS "error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1293:SSL alert number 40"

### ISSUE THREAD

**Issue by wsallem** [bakkerthehacker/bramqp#40]
Hello,
I need help :( 

this is my code : 

'use strict';
var bramqp = require('bramqp');
var tls = require('tls');
var fs = require('fs');
var socket = tls.connect({	
   host : 'Hostname',
    port : port,
    key : fs.readFileSync('cert/cert.pem'),
    ca : [ fs.readFileSync('cert/cacert.pem') ],
    passphrase :'passephrase',   
    secureProtocol :'TLSv1_method'    
    
});

Result : 
vents.js:72
        throw er; // Unhandled 'error' event
              ^
Error: 3074393856:error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1293:SSL alert number 40

    at SlabBuffer.use (tls.js:235:18)
    at CleartextStream.read [as _read] (tls.js:455:29)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at Socket.pipeOnReadable (_stream_readable.js:643:5)

Note : I tried to connect in Php with the same configurations(certif, port, hostname ...) and I managed to connect

Thank you for your help

**Comment by bakkerthehacker** [comment]
Could you post the log from the AMQP server?

I would guess that the `secureProtocol :'TLSv1_method' ` line is causing the issue here.  Is there a reason for it?

**Comment by wsallem** [comment]
Hi,
Thank you for your answer.
I have no access to the log server, but i have all information needed to connect.
I changed protocol TLSv1_method to SSLv3_method , Even I deleted "secureProtocol" from options but have same error
I tried to connect with  2 others lib amqplib and amqp and  I managed to connect, but i wan't work with bramqp "is more stable".

Thank you for your help

**Comment by bakkerthehacker** [comment]
Are there any more details you could provide to help me reproduce this? Which amqp server are you using? What are the versions of the server and client? Are there plugins enabled? How are the keys generated?

You mentioned working code in other amqp libraries.  Could you post an example?

I am happy to help get this working even though it does not directly involve the bramqp library.
