### ISSUE TITLE
Multiple publishes not going through

### ISSUE THREAD

**Issue by giorni** [bakkerthehacker/bramqp#41]
Hi,

I am using the library on node to create some jobs to external machines. I am using version 0.3.2.

The problem I am having is, whenever, at the same request, I do multiple publishes using the same handle, they fail. This is how I am doing this:

```javascript
var bramqp = require('bramqp')
  , net = require('net')
  , async = require('async')

module.exports = new function () {
  var handle
    , socket = net.connect(socketConfig)

  function openConnection() {
    bramqp.initialize(socket, 'rabbitmq/full/amqp0-9-1.stripped.extended', function(err, _handle) {
      handle = _handle

      async.series([function(seriesCallback) {
        handle.openAMQPCommunication('user', 'pass', true, host, seriesCallback);
      }, function(seriesCallback) {
        handle.on('queue.declare-ok', queueReady);
        handle.queue.declare(1, 'q1', false, true, false, false, false, {})
        handle.queue.declare(1, 'q2', false, true, false, false, false, {})
      }],
      function (err) {})
    })
  }

  openConnection()

  this.send = function (message, queue) {
    handle.basic.publish(1, '', queue, true, true, function() {
      handle.content(1, 'basic', {
        'content-type' : 'application/json',
        'delivery-mode' : 2
      }, JSON.stringify(message), function (err) {
      });
    });
  }
}
```

I have tried to implement the basic return method to see if there is anything wrong with rabbit, but I wasn't able to see anything, and I don't think I did it correctly.

As I tried to explain, within the request I can call the send only one time, and it does publish correctly. Consecutive calls fails silently. Other calls to my API do work, and the first send works too.

Do you have any idea on what I am doing wrong here?

**Comment by bakkerthehacker** [comment]
Could you post any error logs from RabbitMQ?

This is most likely an issue with the `basic.publish` method and the content being separated.  When they are separate, it can be possible to send 2 `basic.publish` methods before any content is sent.  To ensure content is written out along with its method, try passing the content directly to the method.  
```javascript
    handle.basic.publish(1, '', queue, true, true, {
        'content-type' : 'application/json',
        'delivery-mode' : 2
      }, JSON.stringify(message), function (err) {
    });
```

**Comment by giorni** [comment]
Thanks again. I made the change you proposed and it worked with mandatory and immediate flags as false. 

As documented, those flags need to be implemented, otherwise, serve fails with this:

```
=ERROR REPORT==== 8-Jun-2015::17:07:56 ===
AMQP connection <0.171.20> (running), channel 1 - error:
{amqp_error,not_implemented,"immediate=true",'basic.publish'}
```

But I am faced with a new problem. I know it is not a directly problem with your library, or RabbitMQ itself, but maybe you already know a good solution for it. Sometimes node restart my process, those are planed, but it doesn't reconnects it back. Publish still goes without any kind of error. Is there a way to check if the socket being used is still up, since it doesn't fails when publishing? Is there a AMQP ping command, or something like that?

The server perceives the lost connection:

```
=ERROR REPORT==== 8-Jun-2015::17:36:15 ===
closing AMQP connection <0.248.20> (179.106.121.34:55194 -> 179.130.22.107:5672):
{inet_error,etimedout}
```

**Comment by bakkerthehacker** [comment]
I am unsure of how your process are being restarted, so I don’t know exactly what to use to restore the AMQP connection.  

AMQP has heartbeats built in, but there will be a delay before realizing the connection is broken.  The socket will emit a `close` event if the network connection is dropped while node is still running.

**Comment by giorni** [comment]
This is the way I am tracking it now, but I wasn't able to reproduce the "problem" anymore.

Thanks a lot for your help.
