### ISSUE TITLE
Buffer error connecting to ActiveMQ docker container

### ISSUE THREAD

**Issue by mark-r-m** [bakkerthehacker/bramqp#45]
## Buffer error connecting to ActiveMQ docker container
Hi folks - I'm getting an error when connecting to a vanilla ActiveMQ docker container. It looks like an issue in **bramqp**

### Original issue raised in AMQPea 
* https://github.com/skybet/amqpea/issues/14

### Example used
Your Hello World example, which works fine on RabbitMQ, but fails on ActiveMQ:
* https://github.com/bakkerthehacker/bramqp/tree/master/tutorial/1%20Hello%20World

### Docker command for my container:
* Assume docker running on 192.168.123.123 in OracleBox. 
* `docker run --name data-activemq -p 1883:1883 -p 5672:5672 -p 8161:8161 -p 61613:61613 -p 61614:61614 -p 61616:61616 -e 'ACTIVEMQ_MIN_MEMORY=512' -e 'ACTIVEMQ_MAX_MEMORY=2048' -v $DATA_PATH/activemq:/data/activemq -h data-activemq -d webcenter/activemq:5.12.0`

### Sender example
With connection modified to 
```javascript
var socket = net.connect({
    host : "192.168.69.100",
    port : 9672
});
```

I get this error
```javascript
$ node ActiveMQ-bramqp-send.js
events.js:85
      throw er; // Unhandled 'error' event
            ^
RangeError: Attempt to allocate Buffer larger than maximum size: 0x3fffffff bytes
    at new Buffer (buffer.js:71:11)
    at FrameParser.parseFrameStart (C:\git\queue-demos\node_modules\bramqp\lib\frameParser.js:367:29)
    at FrameParser.parse (C:\git\queue-demos\node_modules\bramqp\lib\frameParser.js:433:57)
    at Socket.<anonymous> (C:\git\queue-demos\node_modules\bramqp\lib\connectionHandle.js:54:22)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

### Receiver example
As above

Please help!

**Comment by bakkerthehacker** [comment]
Hi! Thanks so much for looking into connecting bramqp in new ways and linking to the amqpea issue. Currently, only RabbitMQ is fully supported, but I would still like to figure out a fix for this. I'm guessing it has to do with some slight differences in the value types used here.

**Comment by bakkerthehacker** [comment]
After looking into this issue, it seems to come from ActiveMQ using AMQP version 1.0.  

bramqp and a few other node clients only support AMQP versions around 0.9.1 which is what RabbitMQ uses.   AMQP 1.0 is quite different and requires quite a bit of change to a library to implement.  Unfortunately, it is unlikely that bramqp will implement connection to AMQP 1.0 brokers any time soon.  

The best solution I can offer here would be to use a different library that supports AMQP 1.0 such as [amqp10](https://github.com/noodlefrenzy/node-amqp10).

**Comment by mark-r-m** [comment]
That's very handy information, thank you!
