### ISSUE TITLE
Request for channel.open example

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [bakkerthehacker/bramqp#48]
Hi!

I would like to ask you to give an example of the **channel.open** function.

I have the following workflow of re-creating the RMQ infrastructure:
1. according to JSON description create a bunch of _exchanges_,
2. according to JSON description create a bunch of _queues_,
3. according to JSON description create _bindings_ among the exchanges and queues

In Python I would establish a separate channel to create each single binding. Now I am curious how to properly create a new _channel_ on the _handler_.

**Comment by bakkerthehacker** [comment]
The best example right now of `channel.open` is from `openAMQPCommunication` [here](https://github.com/bakkerthehacker/bramqp/blob/master/lib/connectionHandle.js#L296..L316).  

If you do not want channel 1 to be opened by `openAMQPCommunication`, you will have to copy the function and replace the necessary parts according to your use case.  Other channels aside from channel 1 can be opened alongside `openAMQPCommunication` after it is finished.

This function does not take any parameters other than the channel number to open on.  Any other methods that you want to send on this channel should use this new channel number.  The channel flow is useful in some cases but not necessary.  

I am in the works on creating advanced tutorials that will have a few different use cases for multiple channels.  See issue #36.  

If you have any more issues or questions, feel free to open another issue or email me.
